# Generated by Django 3.0.4 on 2020-04-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200407_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
