# Generated by Django 3.0.4 on 2020-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200407_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='weight',
        ),
        migrations.AddField(
            model_name='post',
            name='feet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='inches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
